// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWty0O8NmGClwu06E0DHosLLwegDgp7A8',
    appId: '1:763890278994:web:1c4ca775ed461b4a07f58b',
    messagingSenderId: '763890278994',
    projectId: 'oto-asist-2026',
    authDomain: 'oto-asist-2026.firebaseapp.com',
    storageBucket: 'oto-asist-2026.firebasestorage.app',
    measurementId: 'G-YGHXCEPG7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0lOz_8OklYVPobCzG1kw5rxdK4dbVg24',
    appId: '1:763890278994:android:0095edd31d4082e407f58b',
    messagingSenderId: '763890278994',
    projectId: 'oto-asist-2026',
    storageBucket: 'oto-asist-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWty0O8NmGClwu06E0DHosLLwegDgp7A8',
    appId: '1:763890278994:web:1bd2e97f9e4f1c2407f58b',
    messagingSenderId: '763890278994',
    projectId: 'oto-asist-2026',
    authDomain: 'oto-asist-2026.firebaseapp.com',
    storageBucket: 'oto-asist-2026.firebasestorage.app',
    measurementId: 'G-1S0SBLQ2YC',
  );
}
